name: clo_chat_v3
description: Clora - Your AI‑powered period and pregnancy companion.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase Core + Auth + Firestore + Messaging + Storage
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.7.1
  firebase_messaging: ^14.7.17

  # Authentication options
  google_sign_in: ^6.2.1
  intl_phone_number_input: ^0.7.3+1

  # Media & permissions
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  path: ^1.9.0

  # UI & State
  provider: ^6.1.2
  lottie: ^3.1.2
  google_fonts: ^6.1.0

  # Utilities
  intl: ^0.19.0
  http: ^1.4.0
  flutter_secure_storage: ^9.0.0
  flutter_local_notifications: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo/clora_logo.png
    - assets/google_logo.png
    - assets/icons/google_logo.png
    - assets/icons/apple_logo.png
    - assets/images/profile_placeholder.png
    - assets/images/gynecologist_placeholder.png
    - assets/animations/tracker_anim.json

  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
        - asset: assets/fonts/ComicNeue-Bold.ttf
          weight: 700
